# Generated by Django 4.2.7 on 2025-12-02 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Краткий заголовок объявления', max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(help_text='Подробное описание объявления', verbose_name='Описание')),
                ('status', models.CharField(choices=[('OPEN', 'Открыто'), ('CLOSED', 'Закрыто')], default='OPEN', help_text='Текущий статус объявления', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('creator', models.ForeignKey(help_text='Пользователь, создавший объявление', on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='advertiseme_created_923803_idx'), models.Index(fields=['status'], name='advertiseme_status_fbe1c0_idx')],
            },
        ),
    ]
